# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Finn's IB Comp Sci Portfolio"
email: flestrange@isa.aberdeen.sch.uk
description: >- # this means to ignore newlines until "baseurl:"
  IB Computer Science Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://71xx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
search: true
twitter_username: 71xxn
github_username:  71xn
include: ["_pages"]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "air" # "dark", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "Finn Lestrange"
  avatar: "/profile.jpg"
  bio: "IB Computer Science Student" # Note: Markdown is allowed
  location: "UK"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/71xn"
    - label: "HackTheBox"
      icon: "fas fa-fw fa-cube"
      url: "https://www.hackthebox.eu/home/users/profile/210952"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://www.discordapp.com/users/265520638041653248"  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "Contents"
      toc_icon: "fab fa-fw fa-th-list"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
